"""criacao das tabelas

Revision ID: 8c3469889a19
Revises: 
Create Date: 2026-09-27 19:34:55.317341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c3469889a19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Localizacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('tipo_endereco', sa.String(length=20), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('dataCadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Tarefas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tituto', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('dataCadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=False),
    sa.Column('statusTarefas', sa.String(length=20), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tituto')
    )
    op.create_table('ItensTarefa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statusItemTarefa', sa.String(length=20), nullable=False),
    sa.Column('dataConferencia', sa.Date(), nullable=False),
    sa.Column('id_tarefa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tarefa'], ['Tarefas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_itemTarefa', sa.Integer(), nullable=True),
    sa.Column('id_localizacao', sa.Integer(), nullable=True),
    sa.Column('codigoUnico', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('dataCadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_itemTarefa'], ['ItensTarefa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_localizacao'], ['Localizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigoUnico')
    )
    op.drop_table('itenstarefa')
    op.drop_index(op.f('email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('localizacoes')
    op.drop_index(op.f('codigoUnico'), table_name='itens')
    op.drop_table('itens')
    op.drop_index(op.f('tituto'), table_name='tarefas')
    op.drop_table('tarefas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tituto', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dataCadastro', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('prazo', sa.DATE(), nullable=False),
    sa.Column('statusTarefas', mysql.ENUM('Pendante', 'Em_Andamento', 'Concluida'), nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('fk_usuario_tarefa'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('tituto'), 'tarefas', ['tituto'], unique=True)
    op.create_table('itens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_itemTarefa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_localizacao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codigoUnico', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dataCadastro', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_itemTarefa'], ['itenstarefa.id'], name=op.f('fk_itenstarefa_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_localizacao'], ['localizacoes.id'], name=op.f('fk_localizacao_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('codigoUnico'), 'itens', ['codigoUnico'], unique=True)
    op.create_table('localizacoes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cep', mysql.CHAR(length=8), nullable=False),
    sa.Column('logradouro', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('numero', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('complemento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cidade', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estado', mysql.CHAR(length=2), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', mysql.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('tipo_endereco', mysql.ENUM('Residencial', 'Comercial', 'Entrega', 'Cobranca'), server_default=sa.text("'Entrega'"), nullable=True),
    sa.Column('principal', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('dataCadastro', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('perfil', mysql.ENUM('Admin', 'Funcionario'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'usuarios', ['email'], unique=True)
    op.create_table('itenstarefa',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('statusItemTarefa', mysql.ENUM('Pendente', 'Conferido'), nullable=False),
    sa.Column('dataConferencia', sa.DATE(), nullable=False),
    sa.Column('id_tarefa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_tarefa'], ['tarefas.id'], name=op.f('fk_tarefa_itemtarefa'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Itens')
    op.drop_table('ItensTarefa')
    op.drop_table('Tarefas')
    op.drop_table('Usuarios')
    op.drop_table('Localizacoes')
    # ### end Alembic commands ###
