"""criacao das tabelas

Revision ID: joao_baseline_01
Revises: 
Create Date: 2026-09-27 19:34:55.317341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'joao_baseline_01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Localizacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('tipo_endereco', sa.String(length=20), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('dataCadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Tarefas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tituto', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('dataCadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('prazo', sa.Date(), nullable=False),
    sa.Column('statusTarefas', sa.String(length=20), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tituto')
    )
    op.create_table('ItensTarefa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statusItemTarefa', sa.String(length=20), nullable=False),
    sa.Column('dataConferencia', sa.Date(), nullable=False),
    sa.Column('id_tarefa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_tarefa'], ['Tarefas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_itemTarefa', sa.Integer(), nullable=True),
    sa.Column('id_localizacao', sa.Integer(), nullable=True),
    sa.Column('codigoUnico', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('dataCadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_itemTarefa'], ['ItensTarefa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_localizacao'], ['Localizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigoUnico')
    )


def downgrade() -> None:
    op.drop_table('Itens')
    op.drop_table('ItensTarefa')
    op.drop_table('Tarefas')
    op.drop_table('Usuarios')
    op.drop_table('Localizacoes')
